--window message
WM_KEYDOWN               = 0x0100;
WM_KEYUP                 = 0x0101;
WM_CHAR                  = 0x0102;
WM_MOUSEMOVE             = 0x0200;
WM_LBUTTONDOWN           = 0x0201;
WM_LBUTTONUP             = 0x0202;
WM_LBUTTONDBLCLK         = 0x0203;
WM_RBUTTONDOWN           = 0x0204;
WM_RBUTTONUP             = 0x0205;
WM_RBUTTONDBLCLK         = 0x0206;
WM_MBUTTONDOWN           = 0x0207;
WM_MBUTTONUP             = 0x0208;
WM_MBUTTONDBLCLK         = 0x0209;
WM_MOUSEWHEEL            = 0x020A;

--message box type
MB_OK					= 0;
MB_OKCANCEL		= 1;
MB_YESNO			= 4;

--message box command id
IDOK					= 1;
IDCANCEL			= 2;
IDYES         = 6;
IDNO          = 7;

--Aui object
AUISTILLIMAGEBUTTON_STATE_NORMAL  = 0;
AUISTILLIMAGEBUTTON_STATE_CLICK		= 2;

--chat channel
GP_CHAT_LOCAL     = 0;
GP_CHAT_FARCRY    = 1;
GP_CHAT_TEAM      = 2;
GP_CHAT_FACTION   = 3;
GP_CHAT_WHISPER   = 4;
GP_CHAT_DAMAGE    = 5;
GP_CHAT_FIGHT     = 6;
GP_CHAT_TRADE     = 7;
GP_CHAT_SYSTEM    = 8;
GP_CHAT_BROADCAST = 9;
GP_CHAT_MISC      = 10;
GP_CHAT_FAMILY    = 11;
GP_CHAT_GM		  = 12;
GP_CHAT_CAMP	  = 13;
GP_CHAT_DISTRICT  = 14;
GP_CHAT_CUR_MAP   = 15;
GP_CHAT_BATTLE	  = 16;
GP_CHAT_EDICT	  = 17;
GP_CHAT_KILL	  = 18;
GP_CHAT_GANG	  = 19;
GP_CHAT_MAX       = 20;


--game icon type
ICON_TYPE_NULL               = 0;
ICON_TYPE_NORMALITEM         = 1;
ICON_TYPE_EQUIPPACK          = 2;
ICON_TYPE_INVENTORYPACK      = 3;
ICON_TYPE_STORAGEPACK        = 4;
ICON_TYPE_FACTIONSTORAGEPACK = 5;
ICON_TYPE_LOOTPACK           = 6;
ICON_TYPE_QUICKBAR           = 7;

--equip inventory item type
EQUIPIVTR_WEAPON_MELEE    = 0;
EQUIPIVTR_WEAPON_RANGE    = 1;
EQUIPIVTR_BODY            = 2;
EQUIPIVTR_SHOULDER        = 3;
EQUIPIVTR_LEG             = 4;
EQUIPIVTR_FOOT            = 5;
EQUIPIVTR_WAIST           = 6;
EQUIPIVTR_WRIST           = 7;
EQUIPIVTR_HEAD            = 8;
EQUIPIVTR_FINGER1         = 9;
EQUIPIVTR_FINGER2         = 10;
EQUIPIVTR_MANTLE          = 11;
EQUIPIVTR_FASHION_HEAD    = 12;
EQUIPIVTR_FASHION_BODY    = 13;
EQUIPIVTR_FASHION_EYE     = 14;
EQUIPIVTR_FASHION_NOSE    = 15;
EQUIPIVTR_FASHION_LIP     = 16;
EQUIPIVTR_FASHION_EAR     = 17;
EQUIPIVTR_MAIN_TALISMAN   = 18;
EQUIPIVTR_MEDAL           = 19;
EQUIPIVTR_SADDLE          = 20;
EQUIPIVTR_CHEST           = 21;
EQUIPIVTR_COMPASS         = 22;
EQUIPIVTR_CHURINGA1       = 23;
EQUIPIVTR_CHURINGA2       = 24;
EQUIPIVTR_CHURINGA3       = 25;
EQUIPIVTR_CHURINGA4       = 26;
EQUIPIVTR_CHURINGA5       = 27;
EQUIPIVTR_CHURINGA6       = 28;
SIZE_EQUIPIVTR            = 29;

--lua event

LUA_EVENT_TEAM_INVITE         = 10001;
LUA_EVENT_TEAM_REJECTINVITE   = 10002;
LUA_EVENT_TEAM_REQUEST        = 10003;
LUA_EVENT_TEAM_REJECTREQUEST  = 10004;
LUA_EVENT_TEAM_SELFJOIN       = 10005;
LUA_EVENT_TEAM_SELFLEAVE      = 10006;
LUA_EVENT_TEAM_MEMBERJOIN     = 10007;
LUA_EVENT_TEAM_MEMBERLEAVE    = 10008;
LUA_EVENT_TEAM_MEMBERLOGIN    = 10009;
LUA_EVENT_TEAM_MEMBERLOGOUT   = 10010;
LUA_EVENT_TEAM_CHANGELEADER   = 10011;
LUA_EVENT_TEAM_CHANGELOOTRULE = 10012;

LUA_EVENT_RBTNCLICK_PLAYER    = 10101;
LUA_EVENT_RBTNCLICK_MATTER    = 10102;

LUA_EVENT_OPERATION_CANCEL    = 10201;
LUA_EVENT_LOOT_OPEN           = 10202;

LUA_EVENT_LOADING_SETWORLD    = 20001;
LUA_EVENT_LOADING_SETPROGRESS = 20002;

LUA_EVENT_FLOWER_GUIDE = 25000;

--item class id
ICID_EQUIPBASE = 0;
ICID_EQUIP = 1;
ICID_MATERIAL = 2;
ICID_MEDICINE = 3;
ICID_REVSCROLL = 4;
ICID_SKILLTOME = 5;
ICID_TOWNSCROLL = 6;
ICID_TASKITEM = 7;
ICID_ESTONE = 8;
ICID_PSTONE = 9;
ICID_SSTONE = 10;
ICID_TASKDICE = 11;
ICID_TASKNMMATTER = 12;
ICID_ERRORITEM = 13;
ICID_GM_GENERATOR = 14;
ICID_RECIPE = 15;
ICID_FIREWORK = 16;
ICID_REFINETICKET = 17;
ICID_RECIPEROLL = 18;
ICID_TRANSMITROLL = 19;
ICID_LUCKYROLL = 20;
ICID_DOUBLEEXP = 21;
ICID_DESTROYINGESSENCE = 22;
ICID_SKILLMATTER = 23;
ICID_VEHICLE = 24;
ICID_COUPLE_JUMPTO = 25;
ICID_LOTTERY = 26;
ICID_CAMRECORDER = 27;
ICID_TEXT_FIREWORK = 28;
ICID_TALISMAN = 29;
ICID_TALISMAN_EXPFOOD = 30;
ICID_TALISMAN_MERGEKATALYST = 31;
ICID_TALISMAN_ENERGYFOOD = 32;
ICID_SPAKER = 33;
ICID_LEVELUP = 34;

--lua event for secretary system
	LEVT_FIRST_ENTER_GAME				= 30000
	LEVT_FIRST_OPEN_ACCEPT_TASK			= 30001
	LEVT_FIRST_OPEN_PACK				= 30002
	LEVT_FIRST_SWITCHTO_FASHION			= 30003
	LEVT_FIRST_OPEN_SKILL				= 30004

	LEVT_FIRST_KILL_MONSTER				= 30005
	LEVT_FIRST_GAIN_SPEC_ITEM			= 30006
	LEVT_FIRST_USE_SPEC_ITEM			= 30007
	LEVT_FIRST_EQUIP_SPEC_ITEM			= 30008
	LEVT_FIRST_ACCEPT_SPEC_TASK			= 30009

	LEVT_FIRST_FINISH_SPEC_TASK			= 30010
	LEVT_FIRST_FAIL_SPEC_TASK			= 30011
	LEVT_FIRST_COMPLETE_SPEC_TASK = 30012


--condition type for FlowerGuide / ArrowGuide

GUIDE_FINISH_TASK			=		40000
GUIDE_USE_EQUIPMENT			=		40001
GUIDE_RIDING				=		40002
GUIDE_PLAYER_LEVEL_UP		=		40003
GUIDE_POSITION_LEVEL_UP		=		40004
GUIDE_PROFESSION_LEVEL_UP	=		40005
GUIDE_EQUIPMENT_BROKEN		=		40006
GUIDE_LEVEL_UNMATCH			=		40007
GUIDE_LIST_POSITION			=		40008	--查看官职
GUIDE_SET_TITLE				=		40009	--装备称号
GUIDE_GROW_UP				=		40010	--装备成长
GUIDE_LEARN_SKILL			=		40011	--学习技能
